on: [push]
jobs:
  emulator_test: 
    name: Run all tests using Firebase Emulator Suite
    runs-on: ubuntu-latest
    steps:
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm install
      - name: Run all the tests
        working-directory: test
        run: 'firebase emulators:start'
        run: 'npm test'